#!/bin/bash

echo -n "Enter a number between 1 and 3 inclusive > "
read character
case $character in
    1 ) echo "You entered one.";;
    2 ) echo "You entered two.";;
    3 ) echo "You entered three.";;
    * ) echo "You did not enter a number between 1 and 3."
esac


echo -n "Type a digit or a letter > "
read character
case $character in
    [[:lower:]] | [[:upper:]] ) echo "You typed the letter $character";;	# Check for letters
    [0-9] )                     echo "You typed the digit $character";;  	# Check for digits
    * )                         echo "You did not type a letter or a digit" 	# Check for anything else
esac


#The case command has the following form:
##case word in
##    patterns ) commands ;;
##esac
       


